version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "332672892491"
    AWS_DEFAULT_REGION: "us-east-1"
    IMAGE_REPO_NAME: "eduapps/canvascrosslist"
    IMAGE_TAG: "latest"
phases:
  pre_build:
    commands:
    - echo Logging in to ECR...
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
    - echo Build started on `date`
    - echo Building Docker image...
    - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
    - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing Docker image...
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
