version: 0.2

phases:
  install:
    commands:
      # Node, NPM, AWS-CLI are preinstalled on this CodeBuild image.
      - sudo apt-get update -y && sudo apt-get install -y make apt-transport-https
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo apt-get update -y && sudo apt-get install -y yarn
      - yarn install
