/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const GET_COURSES = 'GET_COURSES';
export const GET_COURSES_DONE = 'GET_COURSES_DONE';
export const GET_COURSES_FAIL = 'GET_COURSES_FAIL';
export const GET_COURSE = 'GET_COURSE';
export const GET_COURSE_DONE = 'GET_COURSE_DONE';
export const GET_COURSE_FAIL = 'GET_COURSE_FAIL';
export const SET_XLIST_TARGET = 'SET_XLIST_TARGET';
export const XLIST_SECTION = 'XLIST_SECTION';
export const XLIST_SECTION_FAIL = 'XLIST_SECTION_FAIL';
export const UNXLIST_SECTION = 'UNXLIST_SECTION';
export const UNXLIST_SECTION_FAIL = 'UNXLIST_SECTION_FAIL';
export const XLIST_SECTION_DONE = 'XLIST_SECTION_DONE';
export const UNXLIST_SECTION_DONE = 'UNXLIST_SECTION_DONE';
export const SET_USER = 'SET_USER';
